[package]
name = "qx_rs_err"
version = "0.0.0"
edition = "2021"

[features]
axum = [
    "dep:axum",
    "dep:serde_json"
]

[dependencies]
axum = { version = "^0.8.4", optional = true }
serde_json = { version = "^1.0.140", optional = true }



